// <auto-generated />
namespace project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class acc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(acc));
        
        string IMigrationMetadata.Id
        {
            get { return "202204221341563_acc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
